format = """$directory$git_branch$ruby$php$kotlin$java$golang$c$nodejs$rust$lua$python$character"""


[line_break]
disabled = true

[character]
success_symbol = '[󰠠](bold green) '
error_symbol = '[](bold red) '
vimcmd_symbol = '[󰛿](bold blue) '
vimcmd_replace_one_symbol = '[󰛿](bold purple) '
vimcmd_replace_symbol = '[󰛿](bold purple) '
vimcmd_visual_symbol = '[󰛿](bold yellow) '

[hostname]
disabled = true

[cmd_duration]
min_time = 1
format = "(fg:#161617 bg:#161617)[](fg:#cba6f7 bg:#161617)[ $duration](fg:#161617 bg:#cba6f7)[](fg:#cba6f7 bg:none) "
disabled = true
style = "fg:#cba6f7 bg:#161617"

[directory]
format = "(fg:#161617 bg:#161617)[](fg:#e29eca bg:#161617)[  $path](fg:#161617 bg:#e29eca italic)[](fg:#e29eca bg:none) "
style = "fg:#d9d7d6 bg:#161617"
truncation_length = 2
truncate_to_repo = true

[package]
disabled = true

[git_branch]
format = "(fg:#161617 bg:#161617)[](fg:#e6b99d bg:#161617)[ $branch](fg:#282c34 bg:#e6b99d)[](fg:#e6b99d bg:none) "
style = "fg:#e6b99d bg:#161617"

[python]
format = "(fg:#161617 bg:#161617)[](fg:#90b99f bg:#161617)[${symbol}${pyenv_prefix}(${version})( - ${virtualenv})](fg:#161617 bg:#90b99f)[](fg:#90b99f bg:none) "
style = "fg:#90b99f bg:#161617"
symbol = '󰌠 '

[lua]
format = "(fg:#161617 bg:#161617)[](fg:#92a2d5 bg:#161617)[$symbol$version](fg:#161617 bg:#92a2d5)[](fg:#92a2d5 bg:none) "
style = "fg:#92a2d5 bg:#161617"
symbol = ' '

[rust]
format = "(fg:#161617 bg:#161617)[](fg:#ea83a5 bg:#161617)[$symbol$version](fg:#161617 bg:#ea83a5)[](fg:#ea83a5 bg:none) "
style = "fg:#ea83a5 bg:#161617"
symbol = ' '

[nodejs]
format = "(fg:#161617 bg:#161617)[](fg:#90b99f bg:#161617)[$symbol$version](fg:#161617 bg:#90b99f)[](fg:#90b99f bg:none) "
style = "fg:#90b99f bg:#161617"
symbol = '󰎙 '

[c]
format = "(fg:#161617 bg:#161617)[](fg:#85b5ba bg:#161617)[$symbol$version-$name](fg:#161617 bg:#85b5ba)[](fg:#85b5ba bg:none) "
style = "fg:#85b5ba bg:#161617"
symbol = ' '

[golang]
format = "(fg:#161617 bg:#161617)[](fg:#92a2d5 bg:#161617)[$symbol$version-$name](fg:#161617 bg:#92a2d5)[](fg:#92a2d5 bg:none) "
style = "fg:#92a2d5 bg:#161617"
symbol = ' '

[java]
format = "(fg:#161617 bg:#161617)[](fg:#f5a191 bg:#161617)[$symbol$version-$name](fg:#161617 bg:#f5a191)[](fg:#f5a191 bg:none) "
style = "fg:#f5a191 bg:#161617"
symbol = ' '

[kotlin]
format = "(fg:#161617 bg:#161617)[](fg:##f5a191 bg:#161617)[$symbol$version-$name](fg:#161617 bg:##f5a191)[](fg:##f5a191 bg:none) "
style = "fg:##f5a191 bg:#161617"
symbol = ' '

[php]
format = "(fg:#161617 bg:#161617)[](fg:#92a2d5 bg:#161617)[$symbol$version](fg:#161617 bg:#92a2d5)[](fg:#92a2d5 bg:none) "
style = "fg:#92a2d5 bg:#161617"
symbol = '󰟆 '

[ruby]
format = "(fg:#161617 bg:#161617)[](fg:#e6b99d bg:#161617)[$symbol$version-$name](fg:#161617 bg:#e6b99d)[](fg:#e6b99d bg:none) "
style = "fg:#e6b99d bg:#161617"
symbol = ' '
