format = """$directory$git_branch$ruby$php$kotlin$java$golang$c$nodejs$rust$lua$python$character"""


[line_break]
disabled = true

[character]
success_symbol = '[ğŸˆ](bold green) '
error_symbol = '[ğŸˆ](bold purple) '
vimcmd_symbol = '[ğŸˆ](bold blue) '
vimcmd_replace_one_symbol = '[ğŸˆ](bold purple) '
vimcmd_replace_symbol = '[ğŸˆ](bold purple) '
vimcmd_visual_symbol = '[ğŸˆ](bold yellow) '

[hostname]
disabled = true

[cmd_duration]
min_time = 1
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#cba6f7 bg:#161617)[ï€— $duration](fg:#161617 bg:#cba6f7)[î‚´](fg:#cba6f7 bg:none) "
disabled = true
style = "fg:#cba6f7 bg:#161617"

[directory]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#aca1cf bg:#161617)[ï¼  $path](fg:#161617 bg:#aca1cf italic)[î‚´](fg:#aca1cf bg:none) "
style = "fg:#d9d7d6 bg:#161617"
truncation_length = 2
truncate_to_repo = true

[package]
disabled = true

[git_branch]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#e6b99d bg:#161617)[ï˜ $branch](fg:#282c34 bg:#e6b99d)[î‚´](fg:#e6b99d bg:none) "
style = "fg:#e6b99d bg:#161617"

[python]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#90b99f bg:#161617)[${symbol}${pyenv_prefix}(${version})( - ${virtualenv})](fg:#161617 bg:#90b99f)[î‚´](fg:#90b99f bg:none) "
style = "fg:#90b99f bg:#161617"
symbol = 'ó°Œ  '

[lua]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#92a2d5 bg:#161617)[$symbol$version](fg:#161617 bg:#92a2d5)[î‚´](fg:#92a2d5 bg:none) "
style = "fg:#92a2d5 bg:#161617"
symbol = 'î˜  '

[rust]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#ea83a5 bg:#161617)[$symbol$version](fg:#161617 bg:#ea83a5)[î‚´](fg:#ea83a5 bg:none) "
style = "fg:#ea83a5 bg:#161617"
symbol = 'ïŒ£ '

[nodejs]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#90b99f bg:#161617)[$symbol$version](fg:#161617 bg:#90b99f)[î‚´](fg:#90b99f bg:none) "
style = "fg:#90b99f bg:#161617"
symbol = 'ó°™ '

[c]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#85b5ba bg:#161617)[$symbol$version-$name](fg:#161617 bg:#85b5ba)[î‚´](fg:#85b5ba bg:none) "
style = "fg:#85b5ba bg:#161617"
symbol = 'î˜ '

[golang]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#92a2d5 bg:#161617)[$symbol$version-$name](fg:#161617 bg:#92a2d5)[î‚´](fg:#92a2d5 bg:none) "
style = "fg:#92a2d5 bg:#161617"
symbol = 'î˜§ '

[java]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#f5a191 bg:#161617)[$symbol$version-$name](fg:#161617 bg:#f5a191)[î‚´](fg:#f5a191 bg:none) "
style = "fg:#f5a191 bg:#161617"
symbol = 'ïƒ´ '

[kotlin]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:##f5a191 bg:#161617)[$symbol$version-$name](fg:#161617 bg:##f5a191)[î‚´](fg:##f5a191 bg:none) "
style = "fg:##f5a191 bg:#161617"
symbol = 'î˜´ '

[php]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#92a2d5 bg:#161617)[$symbol$version](fg:#161617 bg:#92a2d5)[î‚´](fg:#92a2d5 bg:none) "
style = "fg:#92a2d5 bg:#161617"
symbol = 'ó°Ÿ† '

[ruby]
format = "(fg:#161617 bg:#161617)[î‚¶](fg:#e6b99d bg:#161617)[$symbol$version-$name](fg:#161617 bg:#e6b99d)[î‚´](fg:#e6b99d bg:none) "
style = "fg:#e6b99d bg:#161617"
symbol = 'îœ¹ '
