format = "$directory$character"
right_format = """$ruby$php$kotlin$java$golang$c$nodejs$rust$lua$python$git_branch$cmd_duration"""

[line_break]
disabled = true

[character]
success_symbol = '[ğŸˆ](bold green) '
error_symbol = '[ğŸˆ](bold red) '
vimcmd_symbol = '[ğŸˆ](bold blue) '
vimcmd_replace_one_symbol = '[ğŸˆ](bold purple) '
vimcmd_replace_symbol = '[ğŸˆ](bold purple) '
vimcmd_visual_symbol = '[ğŸˆ](bold yellow) '

[hostname]
disabled = true

[cmd_duration]
min_time = 1
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#cba6f7 bg:#24273a)[ï€— $duration](fg:#24273a bg:#cba6f7)[î‚´](fg:#cba6f7 bg:none) "
disabled = false
style = "fg:#cba6f7 bg:#24273a"

[directory]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#f5c2e7 bg:#24273a)[ï¼  $path](fg:#24273a bg:#f5c2e7)[î‚´](fg:#f5c2e7 bg:none) "
style = "fg:#d9d7d6 bg:#24273a"
truncation_length = 3
truncate_to_repo = true

[package]
disabled = true

[git_branch]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#f9e2af bg:#24273a)[ï˜ $branch](fg:#282c34 bg:#f9e2af)[î‚´](fg:#f9e2af bg:none) "
style = "fg:#f9e2af bg:#24273a"

[python]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#a6e3a1 bg:#24273a)[${symbol}${pyenv_prefix}(${version} )(${virtualenv} )](fg:#24273a bg:#a6e3a1)[î‚´](fg:#a6e3a1 bg:none) "
style = "fg:#a6e3a1 bg:#24273a"
symbol = 'ï Ÿ '

[lua]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#89b4fa bg:#24273a)[$symbol$version](fg:#24273a bg:#89b4fa)[î‚´](fg:#89b4fa bg:none) "
style = "fg:#89b4fa bg:#24273a"
symbol = 'î˜  '

[rust]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#f38ba8 bg:#24273a)[$symbol$version](fg:#24273a bg:#f38ba8)[î‚´](fg:#f38ba8 bg:none) "
style = "fg:#f38ba8 bg:#24273a"
symbol = 'îš‹ '

[nodejs]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#a6e3a1 bg:#24273a)[$symbol$version](fg:#24273a bg:#a6e3a1)[î‚´](fg:#a6e3a1 bg:none) "
style = "fg:#a6e3a1 bg:#24273a"
symbol = 'ï¢˜ '

[c]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#89dceb bg:#24273a)[$symbol$version-$name](fg:#24273a bg:#89dceb)[î‚´](fg:#89dceb bg:none) "
style = "fg:#89dceb bg:#24273a"
symbol = 'î˜ '

[golang]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#74c7ec bg:#24273a)[$symbol$version-$name](fg:#24273a bg:#74c7ec)[î‚´](fg:#74c7ec bg:none) "
style = "fg:#74c7ec bg:#24273a"
symbol = 'î˜§ '

[java]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#f2cdcd bg:#24273a)[$symbol$version-$name](fg:#24273a bg:#f2cdcd)[î‚´](fg:#f2cdcd bg:none) "
style = "fg:#f2cdcd bg:#24273a"
symbol = 'ïƒ´ '

[kotlin]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#fab387 bg:#24273a)[$symbol$version-$name](fg:#24273a bg:#fab387)[î‚´](fg:#fab387 bg:none) "
style = "fg:#fab387 bg:#24273a"
symbol = 'î˜´ '

[php]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#b4befe bg:#24273a)[$symbol$version-$name](fg:#24273a bg:#b4befe)[î‚´](fg:#b4befe bg:none) "
style = "fg:#b4befe bg:#24273a"
symbol = 'î˜ˆ '

[ruby]
format = "(fg:#24273a bg:#24273a)[î‚¶](fg:#f5e0dc bg:#24273a)[$symbol$version-$name](fg:#24273a bg:#f5e0dc)[î‚´](fg:#f5e0dc bg:none) "
style = "fg:#f5e0dc bg:#24273a"
symbol = 'îœ¹ '
